### PR TITLE
add missing JavaScript source maps (fixes issue #93)

### PR DESCRIPTION
**Pull request by cvan**
for issue #93

### CODE REVIEW

**Comment by caseyyee** [comment]
@lschatzkin this one is ready to merge as well.  Thanks!

**Comment by lschatzkin** [comment]
I just noticed when testing this branch that there's a regression and I'm not sure when it happened. If the user looks around the black background before loading the experiencing, they will trigger the objects. Believe or not, people want to look at the black from different angles (mostly newbies)!

I had fixed this by having all the object location below the big exit circle on the bottom in index.html, and then repositioning to their correct locations once the user clicks on "Get Started".  I'm sure there's a more clever/a-framey way to solve this problem. What would you suggest?

**Comment by caseyyee** [comment]
Filed here: https://github.com/EFForg/spot_the_surveillance/issues/98

Is that what `browserReposition` function is for?  Makes sense now, should be an easy fix!

**Comment by lschatzkin** [comment]
Yep!

**Pull request merged**
