### PR TITLE
attempt playing audio on scene load, fixes #106

### LINKED ISSUE #106: When restarting the experience in VR, the intro and ambient audio does not work.
I believe this is due to the touchdown or mousedown events not firing to start audio.  The rest of the experience functions just fine.

### PR DESCRIPTION
**Pull request by caseyyee**

### CODE REVIEW

**Comment by lschatzkin** [comment]
LGTM! I believe this is the last outstanding item. @caseyyee Please confirm that is true so that I can post all of your hard work live.

**Comment by lschatzkin** [comment]
Also see the new ticket I created...

**Comment by caseyyee** [comment]
Yes, this should be good to go once we land this. Let me know if it fixes the issue in Oculus Browser :)

**Comment by lschatzkin** [comment]
My bad, this totally fixes replay issue. Thanks! Going live shortly!

**Comment by caseyyee** [comment]
Fantastic, thanks!

**Pull request merged**
