### PR TITLE
updates congrats audio element,  fixes issue #88

### PR DESCRIPTION
**Pull request by caseyyee**
https://github.com/EFForg/spot_the_surveillance/issues/88

Will probably adjust this later to work the same way as other audio is loaded now.  For now, this fixes the issue.

### CODE REVIEW

**Comment by caseyyee** [comment]
@lschatzkin please review. Thanks!

**Comment by lschatzkin** [comment]
I'm not sure what's going on, but when I try to review this branch, it acts as if #83 is already merged and throws about of GET errors for the assets.

**Comment by lschatzkin** [comment]
Okay, it's working!

**Comment by caseyyee** [comment]
@lschatzkin I noticed sometimes it may take a second or so till it starts playing, but i think once I get https://github.com/EFForg/spot_the_surveillance/pull/83 fixed up, it should help with that. We may just want to re-write it so that it's in index.html rather than creating all the elements using js.

**Pull request merged**
