### PR TITLE
reposition hotspot elements after Getting Started, fixes #98

### LINKED ISSUE #98: Hotspots should not be triggered when seeing black background
From @lschatzkin 
> I just noticed when testing this branch that there's a regression and I'm not sure when it happened. If the user looks around the black background before loading the experiencing, they will trigger the objects. Believe or not, people want to look at the black from different angles (mostly newbies)!
> 
> I had fixed this by having all the object location below the big exit circle on the bottom in index.html, and then repositioning to their correct locations once the user clicks on "Get Started". I'm sure there's a more clever/a-framey way to solve this problem. What would you suggest?

### PR DESCRIPTION
**Pull request by caseyyee**
@lschatzkin Let me know if this fixes it!

### CODE REVIEW

**Comment by lschatzkin** [comment]
Resolve conflict please!

**Comment by lschatzkin** [comment]
Oh darn, I just noticed another regression. It used to be that the false targets, the bird and the light, the sound was triggered right away (as you planned to do for all surveillance devices).  We decided to have the narration triggered for those  because there is no audio cue.  Should I open a ticket for this?

**Comment by lschatzkin** [comment]
@caseyyee @cvan I just want to take a moment in our busy afternoons to thank you again for all your hard work!

**Comment by caseyyee** [comment]
@lschatzkin rebased!  Should be good to go now.

Yeah, file another ticket for the narration of the bird and light. 

Also, thanks for the Thanks :)

**Pull request merged**
