### PR TITLE
show black environment in Firefox Reality too (like in Oculus Browser)

### PR DESCRIPTION
**Pull request by cvan**
https://github.com/EFForg/spot_the_surveillance/issues/85#issuecomment-465652378

### CODE REVIEW

**Comment by lschatzkin** [comment]
@cvan When I tested this, I am still not seeing the black screen in Firefox Reality.

**Comment by lschatzkin** [comment]
> Same, also not seeing black in FXR.
> 
> If we want to be consistent and just set it so that its starts with the black screen for every platform, then we can remove the conditional altogether.

We'd like to leave the black screen just for mobile devices with no cardboard, as users were getting lost in a sea of black and not clear on where they should look.

**Comment by cvan** [comment]
> We'd like to leave the black screen just for mobile devices with no cardboard, as users were getting lost in a sea of black and not clear on where they should look.

For mobile browsers that do not natively support WebVR (i.e., Safari, Chrome, and Firefox on iOS), A-Frame supports a Cardboard-compatible VR mode when a user clicks the **Enter VR** button.

Would you suggest that we lock the devicemotion-based orientation when a user is viewing on a phone before entering VR? If I'm understanding correctly, that would eliminate the issue you're describing.

No need to answer explicitly, but I'd like to clarify the expected behaviour from your testing and designing of how the flow should be for users in the following scenarios:

- iOS on page load
- iOS in Cardboard pseudo-VR
- Android on page load
- Android in Cardboard pseudo-VR / Daydream WebVR
- Firefox Reality / Oculus Browser / Samsung Internet Browser on Oculus Go on page load
- Firefox Reality / Oculus Browser / Samsung Internet Browser on Oculus Go in WebVR
- desktop (Firefox on Windows / Mac or Chrome Canary on Windows) on page load
- desktop (Firefox on Windows / Mac or Chrome Canary on Windows) in WebVR
- desktop without a VR headset

Hope that helps and that I'm not overwhelming what should be a trivial issue to fix. Heh, let me know, and I'll adjust the PR accordingly. Thank you, @lschatzkin and @caseyyee.

**Comment by lschatzkin** [comment]
> we lock A-Frame's automatic `devicemotion`-based, gyroscope orientation when a user is viewing on a phone before entering VR

What would be great for phone is that, no matter which way they are holding the phone, the intro card/get started is in the middle of their screen. Do you think we could achieve this through determining the gyroscope orientation?

**Comment by cvan** [comment]
> What would be great for phone is that, no matter which way they are holding the phone, the intro card/get started is in the middle of their screen. Do you think we could achieve this through determining the gyroscope orientation?

I started a branch that adds a Welcome screen using the **Get Started** graphic: https://github.com/EFForg/spot_the_surveillance/compare/master...cvan:welcome-page?expand=1

I decided it was overkill for this PR / issue #85. If you think it's appropriate, it might be nice to file an issue for a possible intro page with the project title, a short tagline/summary, and possibly a link to the [announcement blog post](https://www.eff.org/pages/spot-surveillance-vr-experience-keeping-eye-big-brother), and maybe a restyled Enter VR button.

Let me know your thoughts.

Otherwise, this PR is good for another re-review. Thanks!

**Comment by lschatzkin** [comment]
Thank you, works great! Will merge this now.
Also, let me know if you need anything from me for posting this on Reality.

**Comment by cvan** [comment]
@lschatzkin: let me know when you are able to deploy this to prod, and we can feature it in Firefox Reality's Feed. thank you very much.

**Comment by lschatzkin** [comment]
> @lschatzkin: let me know when you are able to deploy this to prod, and we can feature it in Firefox Reality's Feed. thank you very much.

It has already been deployed, yay!

**Pull request merged**
